// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const Layer = "core"
const Title = "KuberCloud ANI Core API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1"

var Operations = []string{
	"listAPIKeys",
	"createAPIKey",
	"revokeAPIKey",
	"logout",
	"beginOIDCLogin",
	"postAuthRefresh",
	"completeOIDCLogin",
	"getBranding",
	"listStorageFilesystems",
	"createStorageFilesystem",
	"deleteStorageFilesystem",
	"getStorageFilesystem",
	"liveness",
	"getInstanceOperation",
	"listInstances",
	"createInstance",
	"getInstance",
	"createInstanceConsoleSession",
	"applyInstanceLifecycle",
	"listInstanceOperations",
	"getMeteringUsage",
	"listNetworkLoadBalancers",
	"createNetworkLoadBalancer",
	"deleteNetworkLoadBalancer",
	"getNetworkLoadBalancer",
	"listNetworkSecurityGroups",
	"createNetworkSecurityGroup",
	"deleteNetworkSecurityGroup",
	"getNetworkSecurityGroup",
	"listNetworkSubnets",
	"createNetworkSubnet",
	"deleteNetworkSubnet",
	"getNetworkSubnet",
	"listNetworkVPCs",
	"createNetworkVPC",
	"deleteNetworkVPC",
	"getNetworkVPC",
	"listStorageObjects",
	"createStorageObject",
	"deleteStorageObject",
	"getStorageObject",
	"readiness",
	"getTasksTaskId",
	"listVectorStores",
	"createVectorStore",
	"deleteVectorStore",
	"getVectorStore",
	"searchVectorStore",
	"listStorageVolumes",
	"createStorageVolume",
	"deleteStorageVolume",
	"getStorageVolume",
}
var Paths = []string{
	"GET /auth/api-keys",
	"POST /auth/api-keys",
	"DELETE /auth/api-keys/{key_id}",
	"POST /auth/logout",
	"POST /auth/oidc/begin",
	"POST /auth/refresh",
	"POST /auth/token",
	"GET /branding",
	"GET /filesystems",
	"POST /filesystems",
	"DELETE /filesystems/{filesystem_id}",
	"GET /filesystems/{filesystem_id}",
	"GET /healthz",
	"GET /instance-operations/{operation_id}",
	"GET /instances",
	"POST /instances",
	"GET /instances/{instance_id}",
	"POST /instances/{instance_id}/console",
	"POST /instances/{instance_id}/lifecycle",
	"GET /instances/{instance_id}/operations",
	"GET /metering/usage",
	"GET /networks/load-balancers",
	"POST /networks/load-balancers",
	"DELETE /networks/load-balancers/{load_balancer_id}",
	"GET /networks/load-balancers/{load_balancer_id}",
	"GET /networks/security-groups",
	"POST /networks/security-groups",
	"DELETE /networks/security-groups/{security_group_id}",
	"GET /networks/security-groups/{security_group_id}",
	"GET /networks/subnets",
	"POST /networks/subnets",
	"DELETE /networks/subnets/{subnet_id}",
	"GET /networks/subnets/{subnet_id}",
	"GET /networks/vpcs",
	"POST /networks/vpcs",
	"DELETE /networks/vpcs/{vpc_id}",
	"GET /networks/vpcs/{vpc_id}",
	"GET /objects",
	"POST /objects",
	"DELETE /objects/{object_id}",
	"GET /objects/{object_id}",
	"GET /readyz",
	"GET /tasks/{task_id}",
	"GET /vector-stores",
	"POST /vector-stores",
	"DELETE /vector-stores/{vector_store_id}",
	"GET /vector-stores/{vector_store_id}",
	"POST /vector-stores/{vector_store_id}/search",
	"GET /volumes",
	"POST /volumes",
	"DELETE /volumes/{volume_id}",
	"GET /volumes/{volume_id}",
}
var Schemas = []string{
	"APIKeyInfo",
	"AsyncTask",
	"BeginOIDCLoginRequest",
	"BeginOIDCLoginResponse",
	"CompleteOIDCLoginRequest",
	"CoreDevProfileInfo",
	"CreateAPIKeyRequest",
	"CreateAPIKeyResponse",
	"CreateInstanceConsoleSessionRequest",
	"CreateInstanceRequest",
	"CreateInstanceResponse",
	"CreateNetworkLoadBalancerRequest",
	"CreateNetworkSecurityGroupRequest",
	"CreateNetworkSubnetRequest",
	"CreateNetworkVPCRequest",
	"CreateStorageFilesystemRequest",
	"CreateStorageObjectRequest",
	"CreateStorageVolumeRequest",
	"CreateVectorStoreRequest",
	"CursorPage",
	"ErrorResponse",
	"HealthCheck",
	"InstanceConsoleSession",
	"InstanceLifecycleRequest",
	"InstanceLifecycleResponse",
	"InstanceListResponse",
	"InstanceOperation",
	"InstanceRecord",
	"ListAPIKeysResponse",
	"LogoutRequest",
	"NetworkLoadBalancer",
	"NetworkLoadBalancerListResponse",
	"NetworkLoadBalancerListener",
	"NetworkResourceState",
	"NetworkSecurityGroup",
	"NetworkSecurityGroupListResponse",
	"NetworkSecurityGroupRule",
	"NetworkSubnet",
	"NetworkSubnetListResponse",
	"NetworkVPC",
	"NetworkVPCListResponse",
	"RefreshAccessTokenRequest",
	"RefreshAccessTokenResponse",
	"RevokeStatusResponse",
	"StorageFilesystem",
	"StorageFilesystemListResponse",
	"StorageObject",
	"StorageObjectListResponse",
	"StorageResourceState",
	"StorageVolume",
	"StorageVolumeListResponse",
	"TokenPairResponse",
	"VectorStore",
	"VectorStoreListResponse",
	"VectorStoreSearchHit",
	"VectorStoreSearchRequest",
	"VectorStoreSearchResponse",
	"VectorStoreState",
	"WorkloadIdentityBinding",
}
var IdempotencyOperations = []string{
	"createStorageFilesystem",
	"createInstance",
	"applyInstanceLifecycle",
	"createNetworkLoadBalancer",
	"createNetworkSecurityGroup",
	"createNetworkSubnet",
	"createNetworkVPC",
	"createStorageObject",
	"createVectorStore",
	"createStorageVolume",
}
var CursorPaginationOperations = []string{
	"listStorageFilesystems",
	"listInstances",
	"listInstanceOperations",
	"listNetworkLoadBalancers",
	"listNetworkSecurityGroups",
	"listNetworkSubnets",
	"listNetworkVPCs",
	"listStorageObjects",
	"listVectorStores",
	"listStorageVolumes",
}
var ErrorCodes = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"FORBIDDEN",
	"INTERNAL_ERROR",
	"NOT_FOUND",
	"NOT_IMPLEMENTED",
	"RATE_LIMIT_EXCEEDED",
	"UNAUTHORIZED",
}

type APIError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Details   map[string]any `json:"details,omitempty"`
}

func (err APIError) Error() string {
	if err.Message == "" {
		return err.Code
	}
	if err.Code == "" {
		return err.Message
	}
	return err.Code + ": " + err.Message
}

type Client struct {
	BaseURL string
	Token   string
}

type RequestOptions struct {
	Body    map[string]any
	Params  map[string]string
	Headers map[string]string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func (client Client) Request(method string, path string, options RequestOptions) (any, error) {
	requestURL, err := client.requestURL(path, options.Params)
	if err != nil {
		return nil, err
	}
	var body io.Reader
	if options.Body != nil {
		payload, err := json.Marshal(options.Body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		body = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(strings.ToUpper(method), requestURL, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if client.Token != "" {
		req.Header.Set("Authorization", "Bearer "+client.Token)
	}
	for key, value := range options.Headers {
		req.Header.Set(key, value)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return decodeResponse(resp)
}

func (client Client) requestURL(path string, params map[string]string) (string, error) {
	base := strings.TrimRight(client.BaseURL, "/")
	relative := "/" + strings.TrimLeft(path, "/")
	parsed, err := url.Parse(base + relative)
	if err != nil {
		return "", err
	}
	query := parsed.Query()
	for key, value := range params {
		if value != "" {
			query.Set(key, value)
		}
	}
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}

func decodeResponse(resp *http.Response) (any, error) {
	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	payload, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(payload) == 0 {
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
		}
		return nil, nil
	}
	var decoded any
	if strings.Contains(resp.Header.Get("Content-Type"), "application/json") {
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return nil, err
		}
	} else {
		decoded = string(payload)
	}
	if resp.StatusCode >= 400 {
		if data, ok := decoded.(map[string]any); ok {
			code, _ := data["code"].(string)
			message, _ := data["message"].(string)
			requestID, _ := data["request_id"].(string)
			details, _ := data["details"].(map[string]any)
			if code != "" && message != "" {
				return nil, APIError{Code: code, Message: message, RequestID: requestID, Details: details}
			}
		}
		return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
	}
	return decoded, nil
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}

func NewIdempotencyKey(prefix string) (string, error) {
	if prefix == "" {
		prefix = "ani"
	}
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return prefix + "_" + hex.EncodeToString(random), nil
}

func WithIdempotencyKey(body map[string]any, key string) (map[string]any, error) {
	if body == nil {
		body = map[string]any{}
	}
	if key == "" {
		generated, err := NewIdempotencyKey("ani")
		if err != nil {
			return nil, err
		}
		key = generated
	}
	body["idempotency_key"] = key
	return body, nil
}

func CursorParams(limit int, cursor string) map[string]string {
	params := map[string]string{}
	if limit > 0 {
		params["limit"] = fmt.Sprintf("%d", limit)
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	return params
}

func IsAPIErrorCode(code string) bool {
	for _, item := range ErrorCodes {
		if item == code {
			return true
		}
	}
	return false
}

func NewAPIError(code string, message string, requestID string, details map[string]any) APIError {
	return APIError{Code: code, Message: message, RequestID: requestID, Details: details}
}
