// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package main

import (
	"fmt"

	anisdk "github.com/kubercloud/ani-sdks/core-go/anisdk"
)

func main() {
	client := anisdk.NewClient("http://127.0.0.1:4010/api/v1", "dev-token")
	body, err := anisdk.WithIdempotencyKey(map[string]any{"name": "demo"}, "example-key")
	if err != nil {
		panic(err)
	}
	params := anisdk.CursorParams(20, "")
	apiErr := anisdk.NewAPIError("BAD_REQUEST", "invalid request", "req_example", nil)
	if client.BaseURL == "" || body["idempotency_key"] == "" || params["limit"] != "20" || apiErr.Error() == "" || !anisdk.IsAPIErrorCode(apiErr.Code) {
		panic("invalid SDK example")
	}
	fmt.Println("core go SDK example ok")
}
