# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import json
import secrets
from urllib import error, parse, request

LAYER = "core"
TITLE = "KuberCloud ANI Core API"
VERSION = "1.0.0"
SERVER_URL = "https://{host}/api/v1"
OPERATIONS = [
    "listAPIKeys",
    "createAPIKey",
    "revokeAPIKey",
    "logout",
    "beginOIDCLogin",
    "postAuthRefresh",
    "completeOIDCLogin",
    "getBranding",
    "listStorageFilesystems",
    "createStorageFilesystem",
    "deleteStorageFilesystem",
    "getStorageFilesystem",
    "liveness",
    "getInstanceOperation",
    "listInstances",
    "createInstance",
    "getInstance",
    "createInstanceConsoleSession",
    "applyInstanceLifecycle",
    "listInstanceOperations",
    "getMeteringUsage",
    "listNetworkLoadBalancers",
    "createNetworkLoadBalancer",
    "deleteNetworkLoadBalancer",
    "getNetworkLoadBalancer",
    "listNetworkSecurityGroups",
    "createNetworkSecurityGroup",
    "deleteNetworkSecurityGroup",
    "getNetworkSecurityGroup",
    "listNetworkSubnets",
    "createNetworkSubnet",
    "deleteNetworkSubnet",
    "getNetworkSubnet",
    "listNetworkVPCs",
    "createNetworkVPC",
    "deleteNetworkVPC",
    "getNetworkVPC",
    "listStorageObjects",
    "createStorageObject",
    "deleteStorageObject",
    "getStorageObject",
    "readiness",
    "getTasksTaskId",
    "listVectorStores",
    "createVectorStore",
    "deleteVectorStore",
    "getVectorStore",
    "searchVectorStore",
    "listStorageVolumes",
    "createStorageVolume",
    "deleteStorageVolume",
    "getStorageVolume"
]
PATHS = [
    "GET /auth/api-keys",
    "POST /auth/api-keys",
    "DELETE /auth/api-keys/{key_id}",
    "POST /auth/logout",
    "POST /auth/oidc/begin",
    "POST /auth/refresh",
    "POST /auth/token",
    "GET /branding",
    "GET /filesystems",
    "POST /filesystems",
    "DELETE /filesystems/{filesystem_id}",
    "GET /filesystems/{filesystem_id}",
    "GET /healthz",
    "GET /instance-operations/{operation_id}",
    "GET /instances",
    "POST /instances",
    "GET /instances/{instance_id}",
    "POST /instances/{instance_id}/console",
    "POST /instances/{instance_id}/lifecycle",
    "GET /instances/{instance_id}/operations",
    "GET /metering/usage",
    "GET /networks/load-balancers",
    "POST /networks/load-balancers",
    "DELETE /networks/load-balancers/{load_balancer_id}",
    "GET /networks/load-balancers/{load_balancer_id}",
    "GET /networks/security-groups",
    "POST /networks/security-groups",
    "DELETE /networks/security-groups/{security_group_id}",
    "GET /networks/security-groups/{security_group_id}",
    "GET /networks/subnets",
    "POST /networks/subnets",
    "DELETE /networks/subnets/{subnet_id}",
    "GET /networks/subnets/{subnet_id}",
    "GET /networks/vpcs",
    "POST /networks/vpcs",
    "DELETE /networks/vpcs/{vpc_id}",
    "GET /networks/vpcs/{vpc_id}",
    "GET /objects",
    "POST /objects",
    "DELETE /objects/{object_id}",
    "GET /objects/{object_id}",
    "GET /readyz",
    "GET /tasks/{task_id}",
    "GET /vector-stores",
    "POST /vector-stores",
    "DELETE /vector-stores/{vector_store_id}",
    "GET /vector-stores/{vector_store_id}",
    "POST /vector-stores/{vector_store_id}/search",
    "GET /volumes",
    "POST /volumes",
    "DELETE /volumes/{volume_id}",
    "GET /volumes/{volume_id}"
]
SCHEMAS = [
    "APIKeyInfo",
    "AsyncTask",
    "BeginOIDCLoginRequest",
    "BeginOIDCLoginResponse",
    "CompleteOIDCLoginRequest",
    "CoreDevProfileInfo",
    "CreateAPIKeyRequest",
    "CreateAPIKeyResponse",
    "CreateInstanceConsoleSessionRequest",
    "CreateInstanceRequest",
    "CreateInstanceResponse",
    "CreateNetworkLoadBalancerRequest",
    "CreateNetworkSecurityGroupRequest",
    "CreateNetworkSubnetRequest",
    "CreateNetworkVPCRequest",
    "CreateStorageFilesystemRequest",
    "CreateStorageObjectRequest",
    "CreateStorageVolumeRequest",
    "CreateVectorStoreRequest",
    "CursorPage",
    "ErrorResponse",
    "HealthCheck",
    "InstanceConsoleSession",
    "InstanceLifecycleRequest",
    "InstanceLifecycleResponse",
    "InstanceListResponse",
    "InstanceOperation",
    "InstanceRecord",
    "ListAPIKeysResponse",
    "LogoutRequest",
    "NetworkLoadBalancer",
    "NetworkLoadBalancerListResponse",
    "NetworkLoadBalancerListener",
    "NetworkResourceState",
    "NetworkSecurityGroup",
    "NetworkSecurityGroupListResponse",
    "NetworkSecurityGroupRule",
    "NetworkSubnet",
    "NetworkSubnetListResponse",
    "NetworkVPC",
    "NetworkVPCListResponse",
    "RefreshAccessTokenRequest",
    "RefreshAccessTokenResponse",
    "RevokeStatusResponse",
    "StorageFilesystem",
    "StorageFilesystemListResponse",
    "StorageObject",
    "StorageObjectListResponse",
    "StorageResourceState",
    "StorageVolume",
    "StorageVolumeListResponse",
    "TokenPairResponse",
    "VectorStore",
    "VectorStoreListResponse",
    "VectorStoreSearchHit",
    "VectorStoreSearchRequest",
    "VectorStoreSearchResponse",
    "VectorStoreState",
    "WorkloadIdentityBinding"
]
IDEMPOTENCY_OPERATIONS = [
    "createStorageFilesystem",
    "createInstance",
    "applyInstanceLifecycle",
    "createNetworkLoadBalancer",
    "createNetworkSecurityGroup",
    "createNetworkSubnet",
    "createNetworkVPC",
    "createStorageObject",
    "createVectorStore",
    "createStorageVolume"
]
CURSOR_PAGINATION_OPERATIONS = [
    "listStorageFilesystems",
    "listInstances",
    "listInstanceOperations",
    "listNetworkLoadBalancers",
    "listNetworkSecurityGroups",
    "listNetworkSubnets",
    "listNetworkVPCs",
    "listStorageObjects",
    "listVectorStores",
    "listStorageVolumes"
]
ERROR_CODES = [
    "BAD_REQUEST",
    "CONFLICT",
    "FORBIDDEN",
    "INTERNAL_ERROR",
    "NOT_FOUND",
    "NOT_IMPLEMENTED",
    "RATE_LIMIT_EXCEEDED",
    "UNAUTHORIZED"
]


class APIError(Exception):
    def __init__(self, code: str, message: str, request_id: str = "", details: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.request_id = request_id
        self.details = dict(details or {})

    def to_dict(self) -> dict:
        payload = {"code": self.code, "message": self.message, "request_id": self.request_id}
        if self.details:
            payload["details"] = self.details
        return payload


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None, timeout: float = 10.0):
        self.base_url = base_url or SERVER_URL
        self.token = token
        self.timeout = timeout

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS

    def request(
        self,
        method: str,
        path: str,
        body: dict | None = None,
        params: dict | None = None,
        headers: dict | None = None,
    ) -> dict | list | str | None:
        req = request.Request(
            self._url(path, params),
            data=self._encode_body(body),
            method=method.upper(),
            headers=self._headers(headers, body is not None),
        )
        try:
            with request.urlopen(req, timeout=self.timeout) as response:
                return self._decode_response(response.read(), response.headers.get("Content-Type", ""))
        except error.HTTPError as exc:
            payload = self._decode_response(exc.read(), exc.headers.get("Content-Type", ""))
            if isinstance(payload, dict) and "code" in payload and "message" in payload:
                raise APIError(
                    str(payload["code"]),
                    str(payload["message"]),
                    str(payload.get("request_id", "")),
                    payload.get("details") if isinstance(payload.get("details"), dict) else None,
                ) from exc
            raise

    def _url(self, path: str, params: dict | None = None) -> str:
        base = self.base_url.rstrip("/")
        relative = "/" + path.lstrip("/")
        query = parse.urlencode({key: value for key, value in (params or {}).items() if value is not None})
        return f"{base}{relative}{'?' + query if query else ''}"

    def _headers(self, headers: dict | None = None, has_body: bool = False) -> dict:
        merged = {"Accept": "application/json"}
        if has_body:
            merged["Content-Type"] = "application/json"
        if self.token:
            merged["Authorization"] = f"Bearer {self.token}"
        merged.update(headers or {})
        return merged

    def _encode_body(self, body: dict | None) -> bytes | None:
        if body is None:
            return None
        return json.dumps(body).encode("utf-8")

    def _decode_response(self, payload: bytes, content_type: str) -> dict | list | str | None:
        if not payload:
            return None
        text = payload.decode("utf-8")
        if "application/json" in content_type:
            return json.loads(text)
        return text


def new_idempotency_key(prefix: str = "ani") -> str:
    prefix = prefix or "ani"
    return f"{prefix}_{secrets.token_hex(16)}"


def with_idempotency_key(body: dict | None = None, key: str | None = None) -> dict:
    payload = dict(body or {})
    payload["idempotency_key"] = key or new_idempotency_key()
    return payload


def cursor_params(limit: int | None = None, cursor: str | None = None) -> dict:
    params = {}
    if limit is not None and limit > 0:
        params["limit"] = limit
    if cursor:
        params["cursor"] = cursor
    return params


def is_api_error_code(code: str) -> bool:
    return code in ERROR_CODES
