// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import { Client, apiError, cursorParams, isAPIErrorCode, withIdempotencyKey } from "../src/index.mjs";

const client = new Client({ baseURL: "http://127.0.0.1:4010/api/v1", token: "dev-token" });
const body = withIdempotencyKey({ name: "demo" }, "example-key");
const params = cursorParams(20);
const error = apiError("BAD_REQUEST", "invalid request", "req_example");

if (!client.baseURL || typeof client.request !== "function" || body.idempotency_key !== "example-key" || params.limit !== "20" || !isAPIErrorCode(error.code)) {
  throw new Error("invalid SDK example");
}

console.log("services typescript SDK example ok");
