# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import json
import secrets
from urllib import error, parse, request

LAYER = "services"
TITLE = "KuberCloud ANI Services API"
VERSION = "1.0.0"
SERVER_URL = "https://{host}/api/v1/svc"
OPERATIONS = [
    "listInferenceServices",
    "createInferenceService",
    "deleteInferenceService",
    "getInferenceService",
    "listKnowledgeBases",
    "createKnowledgeBase",
    "deleteKnowledgeBase",
    "getKnowledgeBase",
    "listKnowledgeBaseDocuments",
    "uploadKnowledgeBaseDocument",
    "deleteKnowledgeBaseDocument",
    "queryKnowledgeBase",
    "streamQueryKnowledgeBase",
    "listModels",
    "createModel",
    "importModel",
    "deleteModel",
    "getModel",
    "createModelVersion"
]
PATHS = [
    "GET /inference-services",
    "POST /inference-services",
    "DELETE /inference-services/{service_id}",
    "GET /inference-services/{service_id}",
    "GET /knowledge-bases",
    "POST /knowledge-bases",
    "DELETE /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}",
    "GET /knowledge-bases/{kb_id}/documents",
    "POST /knowledge-bases/{kb_id}/documents",
    "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
    "POST /knowledge-bases/{kb_id}/query",
    "GET /knowledge-bases/{kb_id}/query/stream",
    "GET /models",
    "POST /models",
    "POST /models/import",
    "DELETE /models/{model_id}",
    "GET /models/{model_id}",
    "POST /models/{model_id}/versions"
]
SCHEMAS = [
    "AsyncTask",
    "CreateInferenceEndpointRequest",
    "CreateModelRequest",
    "CursorPage",
    "ErrorResponse",
    "InferenceEndpoint",
    "InferenceService",
    "KBDocument",
    "KBQueryRequest",
    "KBQueryResponse",
    "KnowledgeBase",
    "Model",
    "ModelVersion"
]
IDEMPOTENCY_OPERATIONS = []
CURSOR_PAGINATION_OPERATIONS = [
    "listModels"
]
ERROR_CODES = [
    "BAD_REQUEST",
    "CONFLICT",
    "FORBIDDEN",
    "NOT_FOUND",
    "UNAUTHORIZED"
]


class APIError(Exception):
    def __init__(self, code: str, message: str, request_id: str = "", details: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.request_id = request_id
        self.details = dict(details or {})

    def to_dict(self) -> dict:
        payload = {"code": self.code, "message": self.message, "request_id": self.request_id}
        if self.details:
            payload["details"] = self.details
        return payload


class Client:
    def __init__(self, base_url: str | None = None, token: str | None = None, timeout: float = 10.0):
        self.base_url = base_url or SERVER_URL
        self.token = token
        self.timeout = timeout

    def has_operation(self, operation_id: str) -> bool:
        return operation_id in OPERATIONS

    def request(
        self,
        method: str,
        path: str,
        body: dict | None = None,
        params: dict | None = None,
        headers: dict | None = None,
    ) -> dict | list | str | None:
        req = request.Request(
            self._url(path, params),
            data=self._encode_body(body),
            method=method.upper(),
            headers=self._headers(headers, body is not None),
        )
        try:
            with request.urlopen(req, timeout=self.timeout) as response:
                return self._decode_response(response.read(), response.headers.get("Content-Type", ""))
        except error.HTTPError as exc:
            payload = self._decode_response(exc.read(), exc.headers.get("Content-Type", ""))
            if isinstance(payload, dict) and "code" in payload and "message" in payload:
                raise APIError(
                    str(payload["code"]),
                    str(payload["message"]),
                    str(payload.get("request_id", "")),
                    payload.get("details") if isinstance(payload.get("details"), dict) else None,
                ) from exc
            raise

    def _url(self, path: str, params: dict | None = None) -> str:
        base = self.base_url.rstrip("/")
        relative = "/" + path.lstrip("/")
        query = parse.urlencode({key: value for key, value in (params or {}).items() if value is not None})
        return f"{base}{relative}{'?' + query if query else ''}"

    def _headers(self, headers: dict | None = None, has_body: bool = False) -> dict:
        merged = {"Accept": "application/json"}
        if has_body:
            merged["Content-Type"] = "application/json"
        if self.token:
            merged["Authorization"] = f"Bearer {self.token}"
        merged.update(headers or {})
        return merged

    def _encode_body(self, body: dict | None) -> bytes | None:
        if body is None:
            return None
        return json.dumps(body).encode("utf-8")

    def _decode_response(self, payload: bytes, content_type: str) -> dict | list | str | None:
        if not payload:
            return None
        text = payload.decode("utf-8")
        if "application/json" in content_type:
            return json.loads(text)
        return text


def new_idempotency_key(prefix: str = "ani") -> str:
    prefix = prefix or "ani"
    return f"{prefix}_{secrets.token_hex(16)}"


def with_idempotency_key(body: dict | None = None, key: str | None = None) -> dict:
    payload = dict(body or {})
    payload["idempotency_key"] = key or new_idempotency_key()
    return payload


def cursor_params(limit: int | None = None, cursor: str | None = None) -> dict:
    params = {}
    if limit is not None and limit > 0:
        params["limit"] = limit
    if cursor:
        params["cursor"] = cursor
    return params


def is_api_error_code(code: str) -> bool:
    return code in ERROR_CODES
