// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package anisdk

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const Layer = "services"
const Title = "KuberCloud ANI Services API"
const Version = "1.0.0"
const ServerURL = "https://{host}/api/v1/svc"

var Operations = []string{
	"listInferenceServices",
	"createInferenceService",
	"deleteInferenceService",
	"getInferenceService",
	"listKnowledgeBases",
	"createKnowledgeBase",
	"deleteKnowledgeBase",
	"getKnowledgeBase",
	"listKnowledgeBaseDocuments",
	"uploadKnowledgeBaseDocument",
	"deleteKnowledgeBaseDocument",
	"queryKnowledgeBase",
	"streamQueryKnowledgeBase",
	"listModels",
	"createModel",
	"importModel",
	"deleteModel",
	"getModel",
	"createModelVersion",
}
var Paths = []string{
	"GET /inference-services",
	"POST /inference-services",
	"DELETE /inference-services/{service_id}",
	"GET /inference-services/{service_id}",
	"GET /knowledge-bases",
	"POST /knowledge-bases",
	"DELETE /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}",
	"GET /knowledge-bases/{kb_id}/documents",
	"POST /knowledge-bases/{kb_id}/documents",
	"DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
	"POST /knowledge-bases/{kb_id}/query",
	"GET /knowledge-bases/{kb_id}/query/stream",
	"GET /models",
	"POST /models",
	"POST /models/import",
	"DELETE /models/{model_id}",
	"GET /models/{model_id}",
	"POST /models/{model_id}/versions",
}
var Schemas = []string{
	"AsyncTask",
	"CreateInferenceEndpointRequest",
	"CreateModelRequest",
	"CursorPage",
	"ErrorResponse",
	"InferenceEndpoint",
	"InferenceService",
	"KBDocument",
	"KBQueryRequest",
	"KBQueryResponse",
	"KnowledgeBase",
	"Model",
	"ModelVersion",
}
var IdempotencyOperations = []string{}
var CursorPaginationOperations = []string{
	"listModels",
}
var ErrorCodes = []string{
	"BAD_REQUEST",
	"CONFLICT",
	"FORBIDDEN",
	"NOT_FOUND",
	"UNAUTHORIZED",
}

type APIError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id"`
	Details   map[string]any `json:"details,omitempty"`
}

func (err APIError) Error() string {
	if err.Message == "" {
		return err.Code
	}
	if err.Code == "" {
		return err.Message
	}
	return err.Code + ": " + err.Message
}

type Client struct {
	BaseURL string
	Token   string
}

type RequestOptions struct {
	Body    map[string]any
	Params  map[string]string
	Headers map[string]string
}

func NewClient(baseURL string, token string) Client {
	if baseURL == "" {
		baseURL = ServerURL
	}
	return Client{BaseURL: baseURL, Token: token}
}

func (client Client) Request(method string, path string, options RequestOptions) (any, error) {
	requestURL, err := client.requestURL(path, options.Params)
	if err != nil {
		return nil, err
	}
	var body io.Reader
	if options.Body != nil {
		payload, err := json.Marshal(options.Body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		body = bytes.NewReader(payload)
	}
	req, err := http.NewRequest(strings.ToUpper(method), requestURL, body)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if client.Token != "" {
		req.Header.Set("Authorization", "Bearer "+client.Token)
	}
	for key, value := range options.Headers {
		req.Header.Set(key, value)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	return decodeResponse(resp)
}

func (client Client) requestURL(path string, params map[string]string) (string, error) {
	base := strings.TrimRight(client.BaseURL, "/")
	relative := "/" + strings.TrimLeft(path, "/")
	parsed, err := url.Parse(base + relative)
	if err != nil {
		return "", err
	}
	query := parsed.Query()
	for key, value := range params {
		if value != "" {
			query.Set(key, value)
		}
	}
	parsed.RawQuery = query.Encode()
	return parsed.String(), nil
}

func decodeResponse(resp *http.Response) (any, error) {
	if resp.StatusCode == http.StatusNoContent {
		return nil, nil
	}
	payload, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if len(payload) == 0 {
		if resp.StatusCode >= 400 {
			return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
		}
		return nil, nil
	}
	var decoded any
	if strings.Contains(resp.Header.Get("Content-Type"), "application/json") {
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return nil, err
		}
	} else {
		decoded = string(payload)
	}
	if resp.StatusCode >= 400 {
		if data, ok := decoded.(map[string]any); ok {
			code, _ := data["code"].(string)
			message, _ := data["message"].(string)
			requestID, _ := data["request_id"].(string)
			details, _ := data["details"].(map[string]any)
			if code != "" && message != "" {
				return nil, APIError{Code: code, Message: message, RequestID: requestID, Details: details}
			}
		}
		return nil, fmt.Errorf("ANI API request failed: %d", resp.StatusCode)
	}
	return decoded, nil
}

func HasOperation(operationID string) bool {
	for _, operation := range Operations {
		if operation == operationID {
			return true
		}
	}
	return false
}

func NewIdempotencyKey(prefix string) (string, error) {
	if prefix == "" {
		prefix = "ani"
	}
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return prefix + "_" + hex.EncodeToString(random), nil
}

func WithIdempotencyKey(body map[string]any, key string) (map[string]any, error) {
	if body == nil {
		body = map[string]any{}
	}
	if key == "" {
		generated, err := NewIdempotencyKey("ani")
		if err != nil {
			return nil, err
		}
		key = generated
	}
	body["idempotency_key"] = key
	return body, nil
}

func CursorParams(limit int, cursor string) map[string]string {
	params := map[string]string{}
	if limit > 0 {
		params["limit"] = fmt.Sprintf("%d", limit)
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	return params
}

func IsAPIErrorCode(code string) bool {
	for _, item := range ErrorCodes {
		if item == code {
			return true
		}
	}
	return false
}

func NewAPIError(code string, message string, requestID string, details map[string]any) APIError {
	return APIError{Code: code, Message: message, RequestID: requestID, Details: details}
}
