/**
 * ANI API client — generated from OpenAPI Spec.
 *
 * DO NOT hand-write fetch calls. Use this client so all requests are type-safe
 * and automatically reflect Spec changes when `make gen-api` is run.
 *
 * Usage:
 *   import { api } from '@/api/client'
 *   const { data, error } = await api.GET('/models', { params: { query: { limit: 20 } } })
 */
import createClient from 'openapi-fetch'
// schema.d.ts is generated by: npx openapi-typescript ../../api/openapi/v1.yaml -o src/api/schema.d.ts
// If this import fails, run: make gen-api
import type { paths } from './schema'

export const api = createClient<paths>({
  baseUrl: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
  },
})

/** Attach a JWT token to all subsequent requests. Call after login. */
export function setAuthToken(token: string) {
  // openapi-fetch supports per-request headers; for a global default,
  // we wrap the middleware approach.
  api.use({
    onRequest(req) {
      req.headers.set('Authorization', `Bearer ${token}`)
      return req
    },
  })
}
