// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import { Client, apiError, cursorParams, isAPIErrorCode, newIdempotencyKey, operations, schemas, title, version, withIdempotencyKey } from "./src/index.mjs";

const client = new Client({ token: "token" });
if (!client.baseURL || !title || !version || schemas.length === 0) {
  throw new Error("invalid SDK metadata");
}
if (!newIdempotencyKey("test").startsWith("test_")) {
  throw new Error("invalid idempotency key helper");
}
if (withIdempotencyKey({ name: "demo" }, "fixed").idempotency_key !== "fixed") {
  throw new Error("invalid idempotency payload helper");
}
const params = cursorParams(20, "next");
if (params.limit !== "20" || params.cursor !== "next") {
  throw new Error("invalid cursor pagination helper");
}
const error = apiError("BAD_REQUEST", "invalid request", "req_test");
if (error.code !== "BAD_REQUEST" || !isAPIErrorCode("BAD_REQUEST")) {
  throw new Error("invalid API error helper");
}
if (typeof client.request !== "function") {
  throw new Error("missing SDK HTTP request helper");
}
if (operations.length === 0) {
  throw new Error("expected generated operations");
}
if (!client.hasOperation("listAPIKeys")) {
  throw new Error("missing expected operation");
}

console.log("core typescript SDK alpha smoke ok");
