// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
package com.kubercloud.ani.services;

import java.security.SecureRandom;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ApiClient {
    private static final HttpClient HTTP = HttpClient.newHttpClient();
    private static final SecureRandom RANDOM = new SecureRandom();
    public static final String LAYER = "services";
    public static final String TITLE = "KuberCloud ANI Services API";
    public static final String VERSION = "1.0.0";
    public static final String SERVER_URL = "https://{host}/api/v1/svc";
    public static final List<String> OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listInferenceServices",
        "createInferenceService",
        "deleteInferenceService",
        "getInferenceService",
        "listKnowledgeBases",
        "createKnowledgeBase",
        "deleteKnowledgeBase",
        "getKnowledgeBase",
        "listKnowledgeBaseDocuments",
        "uploadKnowledgeBaseDocument",
        "deleteKnowledgeBaseDocument",
        "queryKnowledgeBase",
        "streamQueryKnowledgeBase",
        "listModels",
        "createModel",
        "importModel",
        "deleteModel",
        "getModel",
        "createModelVersion"
    ));
    public static final List<String> PATHS = Collections.unmodifiableList(Arrays.asList(
        "GET /inference-services",
        "POST /inference-services",
        "DELETE /inference-services/{service_id}",
        "GET /inference-services/{service_id}",
        "GET /knowledge-bases",
        "POST /knowledge-bases",
        "DELETE /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}",
        "GET /knowledge-bases/{kb_id}/documents",
        "POST /knowledge-bases/{kb_id}/documents",
        "DELETE /knowledge-bases/{kb_id}/documents/{doc_id}",
        "POST /knowledge-bases/{kb_id}/query",
        "GET /knowledge-bases/{kb_id}/query/stream",
        "GET /models",
        "POST /models",
        "POST /models/import",
        "DELETE /models/{model_id}",
        "GET /models/{model_id}",
        "POST /models/{model_id}/versions"
    ));
    public static final List<String> SCHEMAS = Collections.unmodifiableList(Arrays.asList(
        "AsyncTask",
        "CreateInferenceEndpointRequest",
        "CreateModelRequest",
        "CursorPage",
        "ErrorResponse",
        "InferenceEndpoint",
        "InferenceService",
        "KBDocument",
        "KBQueryRequest",
        "KBQueryResponse",
        "KnowledgeBase",
        "Model",
        "ModelVersion"
    ));
    public static final List<String> IDEMPOTENCY_OPERATIONS = Collections.unmodifiableList(Arrays.asList());
    public static final List<String> CURSOR_PAGINATION_OPERATIONS = Collections.unmodifiableList(Arrays.asList(
        "listModels"
    ));
    public static final List<String> ERROR_CODES = Collections.unmodifiableList(Arrays.asList(
        "BAD_REQUEST",
        "CONFLICT",
        "FORBIDDEN",
        "NOT_FOUND",
        "UNAUTHORIZED"
    ));

    private final String baseUrl;
    private final String token;

    public static final class APIError {
        private final String code;
        private final String message;
        private final String requestId;
        private final Map<String, Object> details;

        public APIError(String code, String message, String requestId, Map<String, Object> details) {
            this.code = code;
            this.message = message;
            this.requestId = requestId;
            this.details = details == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(details));
        }

        public String code() {
            return code;
        }

        public String message() {
            return message;
        }

        public String requestId() {
            return requestId;
        }

        public Map<String, Object> details() {
            return details;
        }
    }

    public static final class APIException extends Exception {
        private final APIError apiError;

        public APIException(APIError apiError) {
            super(apiError == null ? "" : apiError.code() + ": " + apiError.message());
            this.apiError = apiError;
        }

        public APIError apiError() {
            return apiError;
        }
    }

    public static final class RequestOptions {
        private final String bodyJson;
        private final Map<String, String> params;
        private final Map<String, String> headers;

        public RequestOptions(String bodyJson, Map<String, String> params, Map<String, String> headers) {
            this.bodyJson = bodyJson;
            this.params = params == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(params));
            this.headers = headers == null ? Collections.emptyMap() : Collections.unmodifiableMap(new HashMap<>(headers));
        }

        public String bodyJson() {
            return bodyJson;
        }

        public Map<String, String> params() {
            return params;
        }

        public Map<String, String> headers() {
            return headers;
        }
    }

    public ApiClient(String baseUrl, String token) {
        this.baseUrl = (baseUrl == null || baseUrl.isEmpty()) ? SERVER_URL : baseUrl;
        this.token = token;
    }

    public String baseUrl() {
        return baseUrl;
    }

    public String token() {
        return token;
    }

    public boolean hasOperation(String operationId) {
        return OPERATIONS.contains(operationId);
    }

    public String request(String method, String path, RequestOptions options) throws IOException, InterruptedException, APIException {
        RequestOptions opts = options == null ? new RequestOptions(null, null, null) : options;
        HttpRequest.Builder builder = HttpRequest.newBuilder(URI.create(requestUrl(path, opts.params())))
                .header("Accept", "application/json");
        if (token != null && !token.isEmpty()) {
            builder.header("Authorization", "Bearer " + token);
        }
        for (Map.Entry<String, String> entry : opts.headers().entrySet()) {
            builder.header(entry.getKey(), entry.getValue());
        }
        String upperMethod = method == null ? "GET" : method.toUpperCase();
        if (opts.bodyJson() == null) {
            builder.method(upperMethod, HttpRequest.BodyPublishers.noBody());
        } else {
            builder.header("Content-Type", "application/json");
            builder.method(upperMethod, HttpRequest.BodyPublishers.ofString(opts.bodyJson()));
        }
        HttpResponse<String> response = HTTP.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() >= 400) {
            throw new APIException(parseAPIError(response.body(), response.statusCode()));
        }
        return response.body();
    }

    private String requestUrl(String path, Map<String, String> params) {
        String base = baseUrl.replaceAll("/+$", "");
        String relative = path == null || path.isEmpty() ? "/" : "/" + path.replaceAll("^/+", "");
        if (params == null || params.isEmpty()) {
            return base + relative;
        }
        StringJoiner query = new StringJoiner("&");
        for (Map.Entry<String, String> entry : params.entrySet()) {
            if (entry.getValue() != null && !entry.getValue().isEmpty()) {
                query.add(URLEncoder.encode(entry.getKey(), StandardCharsets.UTF_8) + "=" + URLEncoder.encode(entry.getValue(), StandardCharsets.UTF_8));
            }
        }
        String encoded = query.toString();
        return encoded.isEmpty() ? base + relative : base + relative + "?" + encoded;
    }

    private static APIError parseAPIError(String body, int statusCode) {
        String code = jsonString(body, "code");
        String message = jsonString(body, "message");
        String requestId = jsonString(body, "request_id");
        if (code == null || code.isEmpty()) {
            code = "HTTP_" + statusCode;
        }
        if (message == null || message.isEmpty()) {
            message = "ANI API request failed";
        }
        return new APIError(code, message, requestId == null ? "" : requestId, null);
    }

    private static String jsonString(String body, String field) {
        if (body == null) {
            return "";
        }
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(field) + "\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"");
        Matcher matcher = pattern.matcher(body);
        return matcher.find() ? matcher.group(1) : "";
    }

    public static String newIdempotencyKey(String prefix) {
        String safePrefix = (prefix == null || prefix.isEmpty()) ? "ani" : prefix;
        byte[] random = new byte[16];
        RANDOM.nextBytes(random);
        StringBuilder encoded = new StringBuilder(random.length * 2);
        for (byte value : random) {
            encoded.append(String.format("%02x", value & 0xff));
        }
        return safePrefix + "_" + encoded;
    }

    public static Map<String, Object> withIdempotencyKey(Map<String, Object> body, String key) {
        Map<String, Object> payload = new HashMap<>();
        if (body != null) {
            payload.putAll(body);
        }
        payload.put("idempotency_key", (key == null || key.isEmpty()) ? newIdempotencyKey("ani") : key);
        return payload;
    }

    public static Map<String, String> cursorParams(int limit, String cursor) {
        Map<String, String> params = new HashMap<>();
        if (limit > 0) {
            params.put("limit", Integer.toString(limit));
        }
        if (cursor != null && !cursor.isEmpty()) {
            params.put("cursor", cursor);
        }
        return params;
    }

    public static boolean isAPIErrorCode(String code) {
        return ERROR_CODES.contains(code);
    }

    public static APIError apiError(String code, String message, String requestId, Map<String, Object> details) {
        return new APIError(code, message, requestId, details);
    }
}
