// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import com.kubercloud.ani.core.ApiClient;

public final class Basic {
    public static void main(String[] args) {
        ApiClient client = new ApiClient("http://127.0.0.1:4010/api/v1", "dev-token");
        java.util.Map<String, Object> body = ApiClient.withIdempotencyKey(null, "example-key");
        java.util.Map<String, String> params = ApiClient.cursorParams(20, "");
        ApiClient.APIError error = ApiClient.apiError("BAD_REQUEST", "invalid request", "req_example", null);
        if (client.baseUrl().isEmpty()
                || !"example-key".equals(body.get("idempotency_key"))
                || !"20".equals(params.get("limit"))
                || error.message().isEmpty()
                || !ApiClient.isAPIErrorCode(error.code())) {
            throw new IllegalStateException("invalid SDK example");
        }
        System.out.println("core java SDK example ok");
    }
}
