# Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
import kubercloud_ani_core as sdk

client = sdk.Client(base_url="http://127.0.0.1:4010/api/v1", token="dev-token")
body = sdk.with_idempotency_key({"name": "demo"}, "example-key")
params = sdk.cursor_params(limit=20)
api_error = sdk.APIError("BAD_REQUEST", "invalid request", "req_example")

assert client.base_url
assert client.has_operation(sdk.OPERATIONS[0])
assert body["idempotency_key"] == "example-key"
assert params["limit"] == 20
assert sdk.is_api_error_code(api_error.code)

print("core python SDK example ok")
