// Code generated by scripts/gen_sdk_alpha.py; DO NOT EDIT.
export const layer = "core" as const;
export const title = "KuberCloud ANI Core API" as const;
export const version = "1.0.0" as const;
export const serverURL = "https://{host}/api/v1" as const;
export const operations = [
  "listAPIKeys",
  "createAPIKey",
  "revokeAPIKey",
  "logout",
  "beginOIDCLogin",
  "postAuthRefresh",
  "completeOIDCLogin",
  "getBranding",
  "listStorageFilesystems",
  "createStorageFilesystem",
  "deleteStorageFilesystem",
  "getStorageFilesystem",
  "liveness",
  "getInstanceOperation",
  "listInstances",
  "createInstance",
  "getInstance",
  "createInstanceConsoleSession",
  "applyInstanceLifecycle",
  "listInstanceOperations",
  "getMeteringUsage",
  "listNetworkLoadBalancers",
  "createNetworkLoadBalancer",
  "deleteNetworkLoadBalancer",
  "getNetworkLoadBalancer",
  "listNetworkSecurityGroups",
  "createNetworkSecurityGroup",
  "deleteNetworkSecurityGroup",
  "getNetworkSecurityGroup",
  "listNetworkSubnets",
  "createNetworkSubnet",
  "deleteNetworkSubnet",
  "getNetworkSubnet",
  "listNetworkVPCs",
  "createNetworkVPC",
  "deleteNetworkVPC",
  "getNetworkVPC",
  "listStorageObjects",
  "createStorageObject",
  "deleteStorageObject",
  "getStorageObject",
  "readiness",
  "getTasksTaskId",
  "listVectorStores",
  "createVectorStore",
  "deleteVectorStore",
  "getVectorStore",
  "searchVectorStore",
  "listStorageVolumes",
  "createStorageVolume",
  "deleteStorageVolume",
  "getStorageVolume"
] as const;
export const paths = [
  "GET /auth/api-keys",
  "POST /auth/api-keys",
  "DELETE /auth/api-keys/{key_id}",
  "POST /auth/logout",
  "POST /auth/oidc/begin",
  "POST /auth/refresh",
  "POST /auth/token",
  "GET /branding",
  "GET /filesystems",
  "POST /filesystems",
  "DELETE /filesystems/{filesystem_id}",
  "GET /filesystems/{filesystem_id}",
  "GET /healthz",
  "GET /instance-operations/{operation_id}",
  "GET /instances",
  "POST /instances",
  "GET /instances/{instance_id}",
  "POST /instances/{instance_id}/console",
  "POST /instances/{instance_id}/lifecycle",
  "GET /instances/{instance_id}/operations",
  "GET /metering/usage",
  "GET /networks/load-balancers",
  "POST /networks/load-balancers",
  "DELETE /networks/load-balancers/{load_balancer_id}",
  "GET /networks/load-balancers/{load_balancer_id}",
  "GET /networks/security-groups",
  "POST /networks/security-groups",
  "DELETE /networks/security-groups/{security_group_id}",
  "GET /networks/security-groups/{security_group_id}",
  "GET /networks/subnets",
  "POST /networks/subnets",
  "DELETE /networks/subnets/{subnet_id}",
  "GET /networks/subnets/{subnet_id}",
  "GET /networks/vpcs",
  "POST /networks/vpcs",
  "DELETE /networks/vpcs/{vpc_id}",
  "GET /networks/vpcs/{vpc_id}",
  "GET /objects",
  "POST /objects",
  "DELETE /objects/{object_id}",
  "GET /objects/{object_id}",
  "GET /readyz",
  "GET /tasks/{task_id}",
  "GET /vector-stores",
  "POST /vector-stores",
  "DELETE /vector-stores/{vector_store_id}",
  "GET /vector-stores/{vector_store_id}",
  "POST /vector-stores/{vector_store_id}/search",
  "GET /volumes",
  "POST /volumes",
  "DELETE /volumes/{volume_id}",
  "GET /volumes/{volume_id}"
] as const;
export const schemas = [
  "APIKeyInfo",
  "AsyncTask",
  "BeginOIDCLoginRequest",
  "BeginOIDCLoginResponse",
  "CompleteOIDCLoginRequest",
  "CoreDevProfileInfo",
  "CreateAPIKeyRequest",
  "CreateAPIKeyResponse",
  "CreateInstanceConsoleSessionRequest",
  "CreateInstanceRequest",
  "CreateInstanceResponse",
  "CreateNetworkLoadBalancerRequest",
  "CreateNetworkSecurityGroupRequest",
  "CreateNetworkSubnetRequest",
  "CreateNetworkVPCRequest",
  "CreateStorageFilesystemRequest",
  "CreateStorageObjectRequest",
  "CreateStorageVolumeRequest",
  "CreateVectorStoreRequest",
  "CursorPage",
  "ErrorResponse",
  "HealthCheck",
  "InstanceConsoleSession",
  "InstanceLifecycleRequest",
  "InstanceLifecycleResponse",
  "InstanceListResponse",
  "InstanceOperation",
  "InstanceRecord",
  "ListAPIKeysResponse",
  "LogoutRequest",
  "NetworkLoadBalancer",
  "NetworkLoadBalancerListResponse",
  "NetworkLoadBalancerListener",
  "NetworkResourceState",
  "NetworkSecurityGroup",
  "NetworkSecurityGroupListResponse",
  "NetworkSecurityGroupRule",
  "NetworkSubnet",
  "NetworkSubnetListResponse",
  "NetworkVPC",
  "NetworkVPCListResponse",
  "RefreshAccessTokenRequest",
  "RefreshAccessTokenResponse",
  "RevokeStatusResponse",
  "StorageFilesystem",
  "StorageFilesystemListResponse",
  "StorageObject",
  "StorageObjectListResponse",
  "StorageResourceState",
  "StorageVolume",
  "StorageVolumeListResponse",
  "TokenPairResponse",
  "VectorStore",
  "VectorStoreListResponse",
  "VectorStoreSearchHit",
  "VectorStoreSearchRequest",
  "VectorStoreSearchResponse",
  "VectorStoreState",
  "WorkloadIdentityBinding"
] as const;
export const idempotencyOperations = [
  "createStorageFilesystem",
  "createInstance",
  "applyInstanceLifecycle",
  "createNetworkLoadBalancer",
  "createNetworkSecurityGroup",
  "createNetworkSubnet",
  "createNetworkVPC",
  "createStorageObject",
  "createVectorStore",
  "createStorageVolume"
] as const;
export const cursorPaginationOperations = [
  "listStorageFilesystems",
  "listInstances",
  "listInstanceOperations",
  "listNetworkLoadBalancers",
  "listNetworkSecurityGroups",
  "listNetworkSubnets",
  "listNetworkVPCs",
  "listStorageObjects",
  "listVectorStores",
  "listStorageVolumes"
] as const;
export const errorCodes = [
  "BAD_REQUEST",
  "CONFLICT",
  "FORBIDDEN",
  "INTERNAL_ERROR",
  "NOT_FOUND",
  "NOT_IMPLEMENTED",
  "RATE_LIMIT_EXCEEDED",
  "UNAUTHORIZED"
] as const;

export interface ClientOptions {
  baseURL?: string;
  token?: string;
}

export interface RequestOptions {
  body?: Record<string, unknown>;
  params?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
}

export interface APIError {
  code: string;
  message: string;
  request_id: string;
  details?: Record<string, unknown>;
}

export class Client {
  readonly baseURL: string;
  readonly token?: string;

  constructor(options: ClientOptions = {}) {
    this.baseURL = options.baseURL || serverURL;
    this.token = options.token;
  }

  hasOperation(operationID: string): boolean {
    return operations.includes(operationID as typeof operations[number]);
  }

  async request<T = unknown>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await fetch(this.url(path, options.params), {
      method: method.toUpperCase(),
      headers: this.headers(options.headers, options.body !== undefined),
      body: options.body === undefined ? undefined : JSON.stringify(options.body),
    });
    const payload = await this.decodeResponse(response);
    if (!response.ok) {
      if (payload && typeof payload === "object" && "code" in payload && "message" in payload) {
        const data = payload as Record<string, unknown>;
        throw apiError(String(data.code), String(data.message), String(data.request_id || ""), data.details as Record<string, unknown> | undefined);
      }
      throw new Error(`ANI API request failed: ${response.status}`);
    }
    return payload as T;
  }

  private url(path: string, params?: RequestOptions["params"]): string {
    const base = this.baseURL.replace(/\/$/, "");
    const relative = path.startsWith("/") ? path : `/${path}`;
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(params || {})) {
      if (value !== undefined) {
        query.set(key, String(value));
      }
    }
    const suffix = query.toString();
    return `${base}${relative}${suffix ? `?${suffix}` : ""}`;
  }

  private headers(headers?: Record<string, string>, hasBody = false): Record<string, string> {
    return {
      Accept: "application/json",
      ...(hasBody ? { "Content-Type": "application/json" } : {}),
      ...(this.token ? { Authorization: `Bearer ${this.token}` } : {}),
      ...(headers || {}),
    };
  }

  private async decodeResponse(response: Response): Promise<unknown> {
    if (response.status === 204) {
      return undefined;
    }
    const text = await response.text();
    if (!text) {
      return undefined;
    }
    const contentType = response.headers.get("content-type") || "";
    return contentType.includes("application/json") ? JSON.parse(text) : text;
  }
}

export function newIdempotencyKey(prefix = "ani"): string {
  const safePrefix = prefix || "ani";
  const cryptoObj = globalThis.crypto;
  if (cryptoObj?.randomUUID) {
    return `${safePrefix}_${cryptoObj.randomUUID()}`;
  }
  const bytes = new Uint8Array(16);
  if (cryptoObj?.getRandomValues) {
    cryptoObj.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i += 1) {
      bytes[i] = Math.floor(Math.random() * 256);
    }
  }
  return `${safePrefix}_${Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("")}`;
}

export function withIdempotencyKey<T extends Record<string, unknown>>(body: T, key = newIdempotencyKey()): T & { idempotency_key: string } {
  return { ...body, idempotency_key: key };
}

export function cursorParams(limit?: number, cursor?: string): Record<string, string> {
  const params: Record<string, string> = {};
  if (limit !== undefined && limit > 0) {
    params.limit = String(limit);
  }
  if (cursor) {
    params.cursor = cursor;
  }
  return params;
}

export function isAPIErrorCode(code: string): boolean {
  return errorCodes.includes(code as typeof errorCodes[number]);
}

export function apiError(code: string, message: string, requestID = "", details?: Record<string, unknown>): APIError {
  return { code, message, request_id: requestID, ...(details ? { details } : {}) };
}
